use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!

target 'ViteWallet_Example' do
  pod 'ViteWallet', :path => '../'

  pod 'BigInt', '3.1.0'
  pod 'ObjectMapper', '3.3.0'
  pod 'CryptoSwift', '0.12.0'
  pod 'Vite_HDWalletKit', :git => 'https://github.com/vitelabs/vite-keystore-ios.git', :tag => '1.2.1'

  pod 'APIKit', '3.2.1'
  pod 'JSONRPCKit', '3.0.0'
  pod 'PromiseKit', '6.5.2'
  pod 'Result', '3.2.4'

  target 'ViteWallet_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['JSONRPCKit', 'APIKit'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
