use_frameworks!
platform :ios, '10.0'
inhibit_all_warnings!

target 'ViteWallet_Example' do
  pod 'ViteWallet', :path => '../'

  pod 'BigInt', '3.1.0'
  pod 'ObjectMapper', '3.3.0'
  pod 'CryptoSwift', '0.12.0'
  pod 'Vite_HDWalletKit', '1.2.0'

  target 'ViteWallet_Tests' do
    inherit! :search_paths

    
  end
end
